name: Deploy LeetCode API to AWS Lambda

on:
  push:
    branches: [master]

env:
  FUNCTION_NAME: leetcode-api-fn
  ROLE_NAME: leetcode-lambda-role
  API_NAME: leetcode-api
  STAGE: prod
  REGION: us-east-1

jobs:
  deployLeetcodeAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend-server/leetcode-api/aws-lambda-service

      - name: Compile TypeScript
        run: npx tsc
        working-directory: backend-server/leetcode-api/aws-lambda-service

      - name: Zip compiled Lambda
        run: |
          cd backend-server/leetcode-api/aws-lambda-service/dist
          zip -r ../../lambda.zip .
          cd -

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Create IAM Role if it doesn't exist
        run: |
          if ! aws iam get-role --role-name $ROLE_NAME; then
            aws iam create-role \
              --role-name $ROLE_NAME \
              --assume-role-policy-document '{
                "Version": "2012-10-17",
                "Statement": [{
                  "Effect": "Allow",
                  "Principal": {"Service": "lambda.amazonaws.com"},
                  "Action": "sts:AssumeRole"
                }]
              }'
            aws iam attach-role-policy \
              --role-name $ROLE_NAME \
              --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          fi

      - name: Get Role ARN
        id: get-role
        run: |
          ROLE_ARN=$(aws iam get-role --role-name $ROLE_NAME --query 'Role.Arn' --output text)
          echo "role_arn=$ROLE_ARN" >> $GITHUB_OUTPUT

      - name: Create or update Lambda function
        run: |
          if aws lambda get-function --function-name $FUNCTION_NAME; then
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://lambda.zip
          else
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs18.x \
              --handler lambda.handler \
              --zip-file fileb://lambda.zip \
              --role ${{ steps.get-role.outputs.role_arn }}
          fi

      - name: Create HTTP API if needed
        id: create-api
        run: |
          API_ID=$(aws apigatewayv2 get-apis --query "Items[?Name=='$API_NAME'].ApiId" --output text)
          if [ -z "$API_ID" ]; then
            API_ID=$(aws apigatewayv2 create-api \
              --name "$API_NAME" \
              --protocol-type HTTP \
              --query 'ApiId' \
              --output text)
          fi
          echo "api_id=$API_ID" >> $GITHUB_OUTPUT

      - name: Create integration with Lambda
        id: create-integration
        run: |
          API_ID=${{ steps.create-api.outputs.api_id }}
          LAMBDA_ARN=$(aws lambda get-function --function-name $FUNCTION_NAME --query 'Configuration.FunctionArn' --output text)
          INTEGRATION_ID=$(aws apigatewayv2 create-integration \
            --api-id $API_ID \
            --integration-type AWS_PROXY \
            --integration-uri arn:aws:apigateway:${{ env.REGION }}:lambda:path/2015-03-31/functions/$LAMBDA_ARN/invocations \
            --payload-format-version 2.0 \
            --query 'IntegrationId' \
            --output text)
          echo "integration_id=$INTEGRATION_ID" >> $GITHUB_OUTPUT

      - name: Add invoke permission for API Gateway
        run: |
          API_ID=${{ steps.create-api.outputs.api_id }}
          aws lambda add-permission \
            --function-name $FUNCTION_NAME \
            --statement-id apigateway-access \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn arn:aws:execute-api:${{ env.REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:$API_ID/*/*/ \
            || echo "Permission already exists"

      - name: Create route /api/leetcode/{username}
        run: |
          API_ID=${{ steps.create-api.outputs.api_id }}
          INTEGRATION_ID=${{ steps.create-integration.outputs.integration_id }}
          if ! aws apigatewayv2 get-routes --api-id $API_ID --query "Items[?RouteKey=='GET /api/leetcode/{username}']"; then
            aws apigatewayv2 create-route \
              --api-id $API_ID \
              --route-key "GET /api/leetcode/{username}" \
              --target integrations/$INTEGRATION_ID
          fi

      - name: Deploy API to stage
        run: |
          API_ID=${{ steps.create-api.outputs.api_id }}
          aws apigatewayv2 create-deployment \
            --api-id $API_ID \
            --description "Auto deployment"
          aws apigatewayv2 create-stage \
            --api-id $API_ID \
            --stage-name $STAGE \
            --auto-deploy
