name: Deploy LeetCode API to AWS Lambda

on:
  push:
    branches: [master]

env:
  FUNCTION_NAME: leetcode-api-fn
  REGION: us-east-1

jobs:
  deployLeetcodeAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend-service/leetcode-api/aws-lambda-service

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_LEETCODE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LEETCODE_SEECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Compile TypeScript
        run: npx tsc
        working-directory: backend-service/leetcode-api/aws-lambda-service

      - name: Zip compiled Lambda
        run: |
          cd backend-service/leetcode-api/aws-lambda-service
          cp package*.json dist/        # copy package.json and package-lock.json to dist
          cd dist
          npm install --omit=dev        # install production dependencies inside dist
          zip -r lambda.zip .           # zip everything: compiled JS + node_modules
          mv lambda.zip ../lambda.zip

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://backend-service/leetcode-api/aws-lambda-service/lambda.zip \
            --region $REGION

      - name: Check zip file exists
        run: ls -lh backend-service/leetcode-api/aws-lambda-service/lambda.zip
